### ISSUE TITLE
remove console.log, or use other way for debugging

### ISSUE THREAD

**Issue by hyrious** [duty-os/nodejs-on-kubernetes#2]
https://github.com/duty-os/nodejs-on-kubernetes/blob/41db3ce8111eb0abfc79183dc6587e1a4ca47627/src/ConfigMapPropertySourceLocator.ts#L19

It's annoying to see them. Maybe use [debug](https://github.com/visionmedia/debug) instead.

**Comment by leavesster** [comment]
close. because no repo use this package any more
